### ISSUE TITLE
FileUtils.copyFile(File,File) copies symlink instead of target and fails

### ISSUE THREAD

**Issue by msimacek** [sonatype/plexus-utils#18]
When the source file argument of copyFile is a symlink and the used JDK version is >= 7, it copies the symlink itself and not the file it's pointing to. This is inconsistent with behavior on JDK < 7 and doesn't work for relative symlinks, as they usually don't point to the same file after being copied and copyFile consequently throws an IOException, because the sizes of source and target don't match.

**Comment by krosenvold** [comment]
This was done for PLXUTILS-172 and caused a too large change in behaviour for my comfort. This affects only version 3.0.21 and I am now reverting the fix in PLXUTILS-172 since it has too many unintended side effects. We will have to find a new solution for copying symlinks and entire directory trees with symlinks, or maybe add a copy.

Fixed in the new master repo
